
version: "3.9"

networks:
  default:

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: trackr
    ports:
      - 5433:5433
    volumes:
      - trackr_postgres_data:/var/lib/postgresql/data

  app:
    platform: "linux/amd64"
    depends_on:
      - db
    image: ghcr.io/zlohbierdcul/trackr:main
    ports:
      - "3008:3008"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@192.168.2.164:5433/trackr

volumes:
  trackr_postgres_data: